---
abstract: 'A caching wrapper around the svnlook command.'
author:
  - 'Gustavo L. de M. Chaves <gnustavo@cpan.org>'
build_requires:
  Cwd: 0
  English: 0
  File::Copy: 0
  File::Path: 0
  File::Temp: 0
  Test::More: 0
  URI::file: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300014, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SVN-Look
requires:
  Carp: 0
  File::Spec::Functions: 0
  List::MoreUtils: 0
  perl: 5.008_000
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/gnustavo/SVN-Look/issues
  homepage: http://search.cpan.org/dist/SVN-Look/
  repository: git://github.com/gnustavo/SVN-Look.git
version: 0.38
