--- #YAML:1.0
name:                SVN-Look
version:             0.12.455
abstract:            A caching wrapper aroung the svnlook command.
license:             ~
author:              
    - Gustavo Chaves <gustavo+perl@gnustavo.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    File::Spec::Functions:         0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
