---
abstract: 'A caching wrapper around the svnlook command.'
author:
  - 'Gustavo L. de M. Chaves <gnustavo@cpan.org>'
build_requires:
  Cwd: 0
  English: 0
  File::Copy: 0
  File::Path: 0
  File::Temp: 0
  Test::More: 0
  URI::file: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300009, CPAN::Meta::Converter version 2.120351'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SVN-Look
requires:
  Carp: 0
  File::Spec::Functions: 0
  strict: 0
  warnings: 0
version: 0.31
