# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         SVN-Look
version:      0.08.360
version_from: lib/SVN/Look.pm
installdirs:  site
requires:
    Switch:                        0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
